version: 0.2
phases:
  install:
    commands:
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/linux/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - apt-get update && apt-get -y install dnsutils jq python3-pip python3-dev && pip3 install --upgrade awscli
    runtime-versions:
      nodejs: 8 
    
  pre_build:
    commands:
      - LABEL=$(echo "bulletin-board-app_$CODEBUILD_RESOLVED_SOURCE_VERSION")
      - export AWS_ACCOUNT=$(echo $CODEBUILD_BUILD_ARN |cut -f5 -d:)
      - export _PROFILE_=${_PROFILE_}
      - ls -l .
      - echo $AWS_ACCOUNT
      - sed -i "s/bulletin-board-app/$LABEL/" ./bulletin-board-app/Templates/Kubernetes_Service.yml
      - sed -i "s/_PROFILE_/$_PROFILE_/g" ./bulletin-board-app/Templates/Kubernetes_Service.yml     
      - sed -i "s/_AWS_ACCOUNT_/$AWS_ACCOUNT/g" ./bulletin-board-app/Templates/Kubernetes_Service.yml
      - sed -i "s/_ENV_/$_ENV_/g" ./bulletin-board-app/Templates/bbapp_Egress_Rule_For_Istio.yml
      - $(aws ecr get-login --no-include-email)
      - export KUBECONFIG=$HOME/.kube/config
  build:
    commands:
      - cd ./bulletin-board-app
      - $(aws ecr get-login --no-include-email)    
      - docker build --tag "$AWS_ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/babelhealth:$LABEL" -f ./Dockerfile .
      - docker push "$AWS_ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/babelhealth:$LABEL"
  post_build:
    commands:
      - CREDENTIALS=$(aws sts assume-role --role-arn arn:aws:iam::$AWS_ACCOUNT:role/EKS_ServiceRole_ReadOnly_Kubernetes --role-session-name codebuild-kubectl --duration-seconds 900)
      - export AWS_ACCESS_KEY_ID="$(echo ${CREDENTIALS} | jq -r '.Credentials.AccessKeyId')"
      - export AWS_SECRET_ACCESS_KEY="$(echo ${CREDENTIALS} | jq -r '.Credentials.SecretAccessKey')"
      - export AWS_SESSION_TOKEN="$(echo ${CREDENTIALS} | jq -r '.Credentials.SessionToken')"
      - export AWS_EXPIRATION=$(echo ${CREDENTIALS} | jq -r '.Credentials.Expiration')
      - aws sts get-caller-identity
      - aws eks update-kubeconfig --name babelhealth
      - kubectl apply -f ./bulletin-board-app/Templates/Kubernetes_Service.yml
      - kubectl apply -f ./bulletin-board-app/Templates/bbapp_Egress_Rule_For_Istio.yml