version: 0.2
phases:
  install:
    commands:
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/linux/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - apt-get update && apt-get -y install dnsutils jq python3-pip python3-dev && pip3 install --upgrade awscli
    runtime-versions:
      nodejs: 8 
    
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
        

artifacts:
	type: zip
    files:
      - bulletin-board-app/app.js
      - bulletin-board-app/index.html
      - bulletin-board-app/package.json
      - bulletin-board-app/node_modules/**/*
      - bulletin-board-app/backend/**/*