apiVersion: apps/v1
kind: Deployment
metadata:
  name: beep-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      beep: web
  template:
    metadata:
      labels:
        beep: web
    spec:
      containers:
      - name: beep-site
        image: mariatest:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: beep-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    beep: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001

