version: 0.2

phases:
 install:
    runtime-versions:
      nodejs: 8 
    
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
        
  build:
    commands:
      - npm run build
      
  artifacts:
  files:
    - app.js
    - index.html
    - package.json
    - node_modules/*
    - backend/*