apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: aws-bb-app
  namespace: babelhealth
  labels:
    app: bb-app
spec:
 hosts:
 - sqs.us-east-1.amazonaws.com
 - s3.us-east-1.amazonaws.com
 - secretsmanager.us-east-1.amazonaws.com
 - sqs.us-east-1.amazonaws.com
 - s3.us-east-1.amazonaws.com
 - "*.us-east-1.amazonaws.com"
 location: MESH_EXTERNAL
 ports:
 - name: http-port
   number: 80
   protocol: HTTP
 - name: https-port
   number: 443
   protocol: HTTPS
 resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: apipa
  namespace: babelhealth
spec:
  hosts:
  - localhost
  addresses:
  - 169.254.169.254
  ports:
  - number: 80
    name: http
    protocol: tcp
  location: MESH_EXTERNAL
  resolution: STATIC
  endpoints:
  - address: 169.254.169.254